# Generated by Django 4.2 on 2023-04-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booked_on',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='p_phone',
        ),
    ]
