# Generated by Django 4.2 on 2023-04-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_bookings_booked_on_remove_bookings_p_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='doc_name',
            new_name='Doctor_name',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='p_email',
            new_name='Patient_email',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='p_name',
            new_name='Patient_name',
        ),
    ]
