# Generated by Django 4.2 on 2023-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_doc_name_bookings_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=255)),
                ('Password1', models.CharField(max_length=255)),
                ('Password2', models.CharField(max_length=255)),
            ],
        ),
    ]
