# Generated by Django 4.2 on 2023-05-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='FirstName',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='register',
            name='LastName',
        ),
    ]
