# Generated by Django 4.2 on 2023-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=255)),
                ('Password1', models.CharField(max_length=255)),
                ('Password2', models.CharField(max_length=255)),
            ],
        ),
    ]
